In [1]:
import numpy as np
from sentence_transformers import SentenceTransformer
from sklearn.metrics.pairwise import cosine_similarity
from responses.psycotic import (
    DIRECT_RESPONSE as PSYCHOTIC_DIRECT,
    ROLEPLAY_RESPONSE as PSYCHOTIC_ROLEPLAY
)
from responses.king_france import (
    DIRECT_RESPONSE as KING_DIRECT,
    ROLEPLAY_RESPONSE as KING_ROLEPLAY
)
from responses.police_officer import (
    DIRECT_RESPONSE as POLICE_DIRECT,
    ROLEPLAY_RESPONSE as POLICE_ROLEPLAY
)

c:\Users\cauec\OneDrive\Área de Trabalho\nlp-assignment\.venv\lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [ ]:
model = SentenceTransformer('all-MiniLM-L6-v2')

In [ ]:
responses = [
    PSYCHOTIC_DIRECT,
    PSYCHOTIC_ROLEPLAY,
    KING_DIRECT,
    KING_ROLEPLAY,
    POLICE_DIRECT,
    POLICE_ROLEPLAY
]

embeddings = model.encode(responses, convert_to_tensor=False)
similarity_matrix = cosine_similarity(embeddings)

print("Cosine Similarity Matrix:")
print(np.round(similarity_matrix, 3))

Cosine Similarity Matrix:
[[1.    0.937 0.954 0.943 0.85  0.977]
 [0.937 1.    0.91  0.899 0.826 0.934]
 [0.954 0.91  1.    0.943 0.91  0.971]
 [0.943 0.899 0.943 1.    0.871 0.958]
 [0.85  0.826 0.91  0.871 1.    0.873]
 [0.977 0.934 0.971 0.958 0.873 1.   ]]

Similarity:
Direct Response vs Roleplay Response: 0.937
Direct Response vs Roleplay Response: 0.954
Direct Response vs Roleplay Response: 0.943
Direct Response vs Roleplay Response: 0.850
Direct Response vs Roleplay Response: 0.977
Direct Response vs Roleplay Response: 0.910
Direct Response vs Roleplay Response: 0.899
Direct Response vs Roleplay Response: 0.826
Direct Response vs Roleplay Response: 0.934
Direct Response vs Roleplay Response: 0.943
Direct Response vs Roleplay Response: 0.910
Direct Response vs Roleplay Response: 0.971
Direct Response vs Roleplay Response: 0.871
Direct Response vs Roleplay Response: 0.958
Direct Response vs Roleplay Response: 0.873
